### ISSUE TITLE
Upgraded to WIn 10 from 7 and am now getting this error

### ISSUE THREAD

**Issue by Chesspieceface** [extesy/DeckTracker#153]
![tracker error](https://user-images.githubusercontent.com/33596507/32698508-143c032c-c75c-11e7-8ab9-e643f51d3e75.jpg)

**Comment by extesy** [comment]
@Chesspieceface Try reinstalling .net from https://www.microsoft.com/net/download/dotnet-framework-runtime/net462

**Comment by Chesspieceface** [comment]
I tried that and it would because it said the current version was newer or already installed, and then I tried the .Net Repair Tool which also couldn't fix the error.

**Comment by extesy** [comment]
@Chesspieceface Do you have `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\error.log` file? What are the latest error entries there?

Also you can try deleting entire `C:\Users\{profile}\AppData\Roaming\UniversalDeckTracker\` folder (but back it up somewhere just in case).

**Comment by Chesspieceface** [comment]
2017-11-13T00:08:27.5915223Z|System.Windows.Markup.XamlParseException: Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception. ---> System.Runtime.InteropServices.COMException: UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.CreateChannels()
   at System.Windows.Media.MediaSystem.ConnectChannels(MediaContext mc)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at System.Windows.Controls.UIElementCollection.Add(UIElement element)
   at System.Windows.Controls.UIElementCollection.System.Collections.IList.Add(Object value)
   at System.Xaml.Schema.XamlTypeInvoker.AddToCollection(Object instance, Object item)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at DeckTracker.App.Main()

**Comment by Chesspieceface** [comment]
Deleting did nothing

**Comment by extesy** [comment]
According to https://blogs.msdn.microsoft.com/dsui_team/2013/11/18/wpf-render-thread-failures/ one of the common causes is video hardware or drivers issues. Anyways, it's not something I can debug and doing in-place upgrade from 7 to 10 (skipping 8 and 8.1) might bring any number of problems. I can only recommend doing a clean install of 10 and updating all drivers to latest versions.

**Comment by Chesspieceface** [comment]
I can't do a clean install, this was a digital upgrade from 7 from Microsoft.  I have disabled and cleaned all .NET components and then reanabled and redownloaded them and the issue persists.

**Comment by Chesspieceface** [comment]
There was no option to Upgrade to 8 and then 8.1 before 10 that's not how Microsoft does things.  .Net framework is an integrated part of Win 10 and very difficult to even repair or uninstall... I've spent hours trying to troubleshoot this... I don't know what more I can do and I've been using your tracker since it was released with no issue.

**Comment by Chesspieceface** [comment]
I got Microsoft to digitally refresh My install and that did resolve the issue

**Comment by extesy** [comment]
Nice! So it was indeed some side-effect of a Windows upgrade. Good to know.
